"""Domain models for recommendations."""

from __future__ import annotations

from pydantic import BaseModel, Field
from src.phases.phase00.output_contract import RecommendationItem, RecommendationResponse


class RestaurantRecommendation(BaseModel):
    """A structured recommendation output shape generated by the LLM."""

    name: str = Field(..., description="Exact name of the restaurant matching the candidate list")
    cuisine: str = Field(default="", description="Cuisine type of the restaurant")
    rating: float | None = Field(default=None, description="Average user rating")
    estimated_cost: int | None = Field(default=None, description="INR cost for two")
    explanation: str = Field(..., description="Personalized explanation of why this restaurant matches the user preferences")


__all__ = [
    "RecommendationItem",
    "RecommendationResponse",
    "RestaurantRecommendation",
]
